site_name: Program Template
site_url: https://example.com
theme:
  name: readthedocs
  
  font: 
    text: "Roboto"
    code: "Fira Code"
  logo: images/DeathStar.jpg
  features:
    - navigation.footer
  
  palette:
    # Darm Mode
    - scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      # Light Mode
    - scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/john-o-raw-38831a21
    - icon: fontawesome/brands/github
      link: https://jor-donegal.github.io/johnoraw.education/

copyright: Copyright Â© 2025, John O'Raw
